# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eaa78da1c76d5796f90b1f8653155bada9b4cce0ee2cf3e66fb1033f22dd187c948814b1e29c7c10120906463d49836111ed195f9676d04a22163aaa2bcb80e2

test:
  secret_key_base: 3fa5de5cc1fe04a79da0460799f03178df4526baf5bb8999b0442fd49782ad97c2dde79c31696d057d670da267694c7f0f04b832a2a8f84725d5cdf3e0e70eca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
